### ISSUE TITLE
Response Messaging

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/open-designs#19]
**Description**
Any message to user after on-click event 

**Acceptance Criteria**
- [ ] Meets plain language requirement for 4th grade level
- [ ] Use pronouns
- [ ] Use Active Voice
- [ ] Front load important stuff
- [ ] Use bullets or numbered lists
- [ ] Use clear headlines in sub-heads
- [ ] Any message to user after on-click event 
- [ ] High level message
- [ ] Low level message
- [ ] Validation message
