### ISSUE TITLE
Provider Search

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/open-designs#2]
> [Open in MURAL](https://app.mural.co/t/paladinarcher0959/m/paladinarcher0959/1597858034269?wid=0-1598380094189) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> Affinity Cluster #2 - PALADIN & ARCHER
  
**Description:** 
Users are able to search for providers

**Benefit Hypothesis:** 
Being able to find the best provider that fits the realist and protector personas user needs.
This new search will produce better results, with less time spent searching, compared with what currently is available on the market.

**Acceptance Criteria:** 

- [ ]  A user can find a provider

- [ ] Given the user is logged on allow them to select who needs to visit provider

- [ ] A user can search by location & limit by proximity

- [ ] User can specify Dr. Name

- [ ] User can search based on specialty

- [ ] User can search if Dr is in network

- [ ] Search results will include a provider competency rating

- [ ] Search by provider type 

   
**Non-functional requirements:** 

- [ ] Search results produced within 1 second
