### ISSUE TITLE
MVP To Point New Veterans to Services Available

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/open-designs#21]
**Description:**
HMW create a streamlined way to point new Veterans to all the services available?

**Business Outcomes:** 

For Ewardo, Cynthia, and Timothy persona's
who need to understand all the VA services available to them in a simple and intuitive streamlined way
the <solution>
is a <something – the ‘how’>
that <provides this value>
unlike <competitor, current solution or non-existing solution>
our solution <does something better — the ‘why’>

**Leading Indicators:** 

- [ ] system usability score (SUS) upper 70% over 6 weeks

- [ ] User feedback survey over 70% indicating that our service has created a streamlined (minimum "clicks") way to point veterans to services available.

**Nonfunctional Requirements (NFRs):**

- [ ] follow Google benchmarks

- [ ]
