### ISSUE TITLE
"Guru" Provider Selection MVP

### ISSUE THREAD

**Issue by moroni-pickering** [paladinarcher/open-designs#7]
**Description:**
	A web application that will quickly find highly competent medical providers near you.

For the realist and protector users
who need to select a competent healthcare provider
the Guru Provider Selection App
is a mobile first web application
that provides an excellent user experience for finding and selecting the best healthcare provider for your needs, in under 5 minutes
unlike Zocdoc
our solution will include more than customer reviews in a providers rating, we will include the provider's competency rating, our solution will also provide a superior user experience. 
> Diagnostic error is a potential challenge for virtually all medical specialties. The overall misdiagnosis rate is approximately 10% to 15%. 

Our application will facilitate finding the most competent providers ([see reference](https://www.ncbi.nlm.nih.gov/books/NBK499956/#:~:text=Diagnostic%20error%20is%20a%20potential,approximately%2010%25%20to%2015%25.&text=Clinicians%20should%20be%20aware%20of,seek%20and%20confirm%20the%20diagnosis)).

**Business Outcomes:** 

We will become the number 1 tool used by the USA to search for a medical provider

**Leading Indicators:** 

- [ ] User sign ups grow exponentially

- [ ] 90% Repeat users

- [ ] Time spent finding and selecting a provider is less than 5 minutes

**Nonfunctional Requirements (NFRs):**

- [ ] public facing pages must load in 1 second or less

- [ ] 508 Accessibility compliant
