### ISSUE TITLE
Third Party Provider Rating

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/open-designs#8]
**Description:** 
Users can view third party provider ratings that includes a competency element

**Benefit Hypothesis:** 
Users will be able to make better informed decisions about how competent a provider is.

**Acceptance Criteria:** 

- [ ] Ability to view third party ratings

- [ ] Ability to filter by third party ratings

- [ ] Ability to sort third party ratings

- [ ] Third party content is consistent 

   
**Non-functional requirements:** 

- [ ] Integration using an API with a provider that allows us to pull in reviews vs linking them out. 

- [ ] Costs must be viable 

- [ ] Third party API performance must be viable
